
nota1 = int(input("Informe a nota do Primeiro bimestre:"))
nota2 = int(input("Informe a nota do Segundo bimestre:"))
nota3 = int(input("Informe a nota do Terceiro bimestre:"))
nota4 = int(input("Informe a nota do Quarto bimestre:"))

media = (nota1 + nota2 + nota3 + nota4) / 4

if nota1 <= 10 and nota2 <= 10 and nota3 and 10 <= nota4:
    print('media: {}'.format(media))
else:
    print('Foi informado alguma nota errada!')
















"""num1 = int(input('Primeiro valor: '))

num2 = int(input('Segundo valor: '))

num3 = int(input('Terceiro valor: '))



if num1 > num2 and  num1 > num3:
    print('O maior número é {}'.format(num1))
elif num2 > num1 and num2 > num3:
    print('O mairo número é {}'.format(num2))
else:
    print('O maior número é {}'.format(num3))
print('Final do progama! ')"""
